### ISSUE TITLE
esc and sub characters visible

### ISSUE THREAD

**Issue by srvarey** [sjlevine/atom-slime#66]
![atom-problem](https://user-images.githubusercontent.com/326352/35282339-86ebfb8e-0055-11e8-8c80-531a7f5a5305.jpg)

I am using atom with lisp
and in the repl I always get these characters after executing any form e.g. (+ 2 3)

esc 3 sub esc

"hello world"
esc hello world sub esc

Hiding invisibles does nothing to stop 
Would appreciate any help - otherwise back to emacs

I installed
atom-slime
lisp-paredit
language-lisp

I have tried this on 2 windows machines and one linux machine
same problem on all 3

**Comment by vindarel** [comment]
related to https://github.com/sjlevine/atom-slime/issues/64 ?

It's ok with me, I have Atom 1.18.0 on linux x64, Atom-Slime 2.8.0, language-common-lisp 0.9.5, lisp-paredit 0.6.0.

Can you tell your packages versions ?

**Comment by sjlevine** [comment]
Hi all, thanks for the comments, and apologies on my slow reply (been quite busy).

The root of this problem is the way in which `atom-slime` handles syntax highlighting. Special (usually invisible) characters are inserted into the REPL, which then trigger Atom's grammar scope highlighting to change their color appropriately. I agree this isn't the best way to do things though, and I believe in a recent release of Atom they've introduced a new `text` type decoration that would be a better way to handle syntax highlighting in the REPL.

**Comment by sjlevine** [comment]
(Interestingly though, my version doesn't show those characters -- wonder why it appears for some but not others)

**Comment by srvarey** [comment]
Thanks for your reply
I am using
atom-slime 2.8.0
language-lisp 0.2.0
 lisp-paredit 0.6.0

I see you are using language-common-lisp 0.9.5 and I was using
language-list.
I switched but still get same problem

**Comment by srvarey** [comment]
[image: Inline image 1]

**Comment by srvarey** [comment]
Forgot to mention i have atom 1.23.3

**Comment by sjlevine** [comment]
Fixed by #78!

**Comment by BlueManCZ** [comment]
Hello, I have similar problem on Linux. Look on this picture:

![Screenshot](https://user-images.githubusercontent.com/17854950/54766974-8e22d500-4bfc-11e9-8d95-b895eefe59df.png)

**System:**
Linux 4.19.0-2-amd64 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux

**Versions of packages:**
atom [1.35.1 x64](https://github.com/atom/atom/releases/tag/v1.35.1)
atom-slime [2.8.0](https://github.com/sjlevine/atom-slime/releases/tag/v2.8.0)
slime [2.23](https://github.com/slime/slime/releases/tag/v2.23)

**Comment by neil-lindquist** [comment]
As mentioned in #80, the fix is in master, but @sjlevine hasn't made a new release since this was added to master.  You can use the fixed version by using [Atom's package development mode](https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/) and using the master branch
