### ISSUE TITLE
Package current status

### ISSUE THREAD

**Issue by pcr910303** [sjlevine/atom-slime#77]
Well, I saw this project about half a year ago, and is using on a daily basis(well, studying CL).
I *can* use emacs, and I could, but by this package I was happily using atom.
However after seeing the deprecated warning in atom about the deprecated use of "undo option"and came to the repo, I found out the last commit was 2 years ago ;-(
Is this package maintained?
May I ask anyone(maintainers) about current status about this package?

**Comment by vindarel** [comment]
@sjlevine Would you add contributors in ? This PR https://github.com/sjlevine/atom-slime/pull/76 looks neat and is waiting for your input. Maybe after you reviewed neil-lindquist's work once he could help you maintain the repo and add features in. my 2c.

**Comment by pcr910303** [comment]
@sjlevine Great to see it's not deprecated or so! Please don't think I'm offending someone I was just curios(and my english skills  **are**  bad....thanks for such a great package!



_[FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)을 사용하여 Galaxy S8+에서 보냈습니다_

**Comment by neil-lindquist** [comment]
I'd be willing to help with this.  One thought, if you won't have the time to work on this for the indefinate future, would it be worth transferring to @slime or somewhere else where it might be able to get more attention?

**Comment by neil-lindquist** [comment]
@sjlevine can something be figured out for maintaining this package (and swank-client-js) until you  have the time to maintain it yourself again? I am willing to help with the maintenance, and should be able to make the time, if you want help.
These is a great project, but the fact that it hasn't been maintained for the past two years makes it hard to advocate using it.  Something should be figured out to at least address pull requests (especially small ones, like #71).

**Comment by sjlevine** [comment]
Hi @neil-lindquist, thanks for your offer to help out! Let's hold off on transferring ownership of anything for now, because I'm hopeful I'll have some time in a few months to work on this more then. If not, re can re-evaluate then. 

In the mean time for people who want to get some of the changes sooner before I get the time to merge into master, I encourage you to set up a dev package in atom with the correct branch of this repo -- that should work.

**Comment by vindarel** [comment]
> transferring ownership

(just in case, you can give developer rights while keeping ownership (sorry if it's obvious :D ))

because there's still the pb of addressing (small) PRs.

regards

**Comment by neil-lindquist** [comment]
Looking at my previous comments, I did a bad job at explicitly expressing my thoughts.  I was thinking more along the lines of adding contributers or setting up a policy if certain/enough people review a PR and give it a green light, then it could be merged without needing much of your time (either using github's tooling or an informal policy).
My comment about transfering ownership was only ment as food for thought.

**Comment by neil-lindquist** [comment]
Due to the lack of maintenance and communication, I have forked atom-slime to the [SLIMA](https://github.com/neil-lindquist/slima) (Superior Lisp Interation Mode for Atom) package, as well as swank-client-js to [swank-client](https://github.com/neil-lindquist/swank-client).  Currently, its basically the same as atom-slime with the pull requests I created, but I plan to continue improving it in the near future.

**Comment by sjlevine** [comment]
Hi @neil-lindquist, my apologies on the slow reply. Since finishing my PhD thesis and starting a new job, I unfortunately haven't had much time to work on this project. 

I wish you the best of luck in helping maintain this project! I'll add a pointer to the README.md redirecting to your repository as a more recently maintained version.

All the best,
Steve

**Comment by sjlevine** [comment]
Done -- just added a redirect link in the README.
